Refactor: remove portal
equinor/create-dm-app pull request #8
Opened 2022-10-11 13:42 UTC by netr0m

2022-10-13 10:08 UTC, eoaksnes approved these changes

2022-10-13 10:49 UTC, soofstad requested changes

2022-10-13 10:49 UTC, soofstad commented on src/App.tsx
> +          <Route
I don't think there should be any "Routes" in here. If an app needs different routes, thats a part of that app.
This "Bootstrapper" should just render the "app plugin" directly.

2022-10-13 10:49 UTC, soofstad commented on src/app-settings.json
> +  "applicationId": "4483c9b0-d505-46c9-a157-94c79f4d7a6a"
These should be combined into one "absolute ref".
The dataSourceId should not be needed for anything else than fetching this first AppSettings entity.

2022-10-13 13:18 UTC, soofstad approved these changes

2022-10-14 10:59 UTC, netr0m commented
- Awaiting equinor/dm-cli#13

2022-10-17 06:28 UTC, eoaksnes approved these changes
Good work

2022-10-17 08:39 UTC, KristianKjerstad approved these changes

2022-10-17 10:45 UTC, merged